// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO1R3rsY_8dT9F4-ihc4nvNQy9L1CZDe0',
    appId: '1:700211338293:web:a1b0c1cdc533bdae7be57c',
    messagingSenderId: '700211338293',
    projectId: 'heart-disease-detection-69b45',
    authDomain: 'heart-disease-detection-69b45.firebaseapp.com',
    storageBucket: 'heart-disease-detection-69b45.firebasestorage.app',
    measurementId: 'G-K93FT6ZR67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSBwobHtoiVmDi15BEq9rgFjE-6xd320',
    appId: '1:700211338293:android:a7746e27f0e09fa77be57c',
    messagingSenderId: '700211338293',
    projectId: 'heart-disease-detection-69b45',
    storageBucket: 'heart-disease-detection-69b45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OnWPgzhyWCyckeS3_KR2QF5nltdsfNw',
    appId: '1:700211338293:ios:b7d09b080e752e0f7be57c',
    messagingSenderId: '700211338293',
    projectId: 'heart-disease-detection-69b45',
    storageBucket: 'heart-disease-detection-69b45.firebasestorage.app',
    iosBundleId: 'com.example.heartDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3OnWPgzhyWCyckeS3_KR2QF5nltdsfNw',
    appId: '1:700211338293:ios:b7d09b080e752e0f7be57c',
    messagingSenderId: '700211338293',
    projectId: 'heart-disease-detection-69b45',
    storageBucket: 'heart-disease-detection-69b45.firebasestorage.app',
    iosBundleId: 'com.example.heartDiseaseDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO1R3rsY_8dT9F4-ihc4nvNQy9L1CZDe0',
    appId: '1:700211338293:web:5c4e8f52b50bc6537be57c',
    messagingSenderId: '700211338293',
    projectId: 'heart-disease-detection-69b45',
    authDomain: 'heart-disease-detection-69b45.firebaseapp.com',
    storageBucket: 'heart-disease-detection-69b45.firebasestorage.app',
    measurementId: 'G-4113JYVHSJ',
  );

}